/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{js,jsx,ts,tsx}', './components/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        pantone: {
          'cloud-dancer': '#E8E6E1',
          'veiled-vista': '#B8D4C8',
          'baltic-sea': '#7AB6D9',
          'golden-mist': '#D9D4A8',
          'quiet-violet': '#9B8BA8',
          'cloud-cover': '#8B7E74',
          hematite: '#6B5F56',
          'blue-fusion': '#5A6B7A',
          'soft-pink': '#F4C2D7',
          'tender-peach': '#FFDAB9',
        },
        primary: {
          DEFAULT: '#5A6B7A',
          light: 'rgba(90, 107, 122, 0.14)',
          dark: '#7AB6D9',
        },
        background: {
          DEFAULT: '#E8E6E1',
          dark: '#131416',
        },
        card: {
          DEFAULT: '#F7F5F2',
          dark: '#1C1D21',
        },
        elevated: {
          DEFAULT: '#FFFFFF',
          dark: '#25272C',
        },
        content: {
          DEFAULT: '#1F2329',
          secondary: '#596271',
          tertiary: '#7E8796',
          dark: '#D7DAE1',
          'dark-secondary': '#A1A7B3',
        },
        border: {
          DEFAULT: '#D7D8DC',
          dark: '#32353C',
        },
        success: { DEFAULT: '#34C759', dark: '#30D158' },
        warning: { DEFAULT: '#FF9500', dark: '#FF9F0A' },
        danger: { DEFAULT: '#FF1744', dark: '#FF1744' },
        info: { DEFAULT: '#5856D6', dark: '#5E5CE6' },
        tab: {
          DEFAULT: '#F7F5F2',
          dark: '#1C1D21',
          active: '#5A6B7A',
          'active-dark': '#7AB6D9',
          inactive: '#8E8E93',
        },
      },
      spacing: {
        screen: '24px',
        18: '72px',
        22: '88px',
      },
      letterSpacing: {
        'korean-tight': '-0.02em',
        'korean-normal': '-0.01em',
      },
      borderRadius: {
        xs: '6px',
        sm: '10px',
        md: '14px',
        lg: '20px',
        xl: '28px',
      },
      fontSize: {
        'title-lg': ['34px', { lineHeight: '41px', fontWeight: '700', letterSpacing: '-0.01em' }],
        'title-1': ['24px', { lineHeight: '30px', fontWeight: '700', letterSpacing: '-0.01em' }],
        'title-2': ['22px', { lineHeight: '28px', fontWeight: '700', letterSpacing: '-0.01em' }],
        'title-3': ['20px', { lineHeight: '25px', fontWeight: '600', letterSpacing: '-0.01em' }],
        headline: ['17px', { lineHeight: '22px', fontWeight: '600', letterSpacing: '-0.01em' }],
        body: ['16px', { lineHeight: '22px', fontWeight: '400', letterSpacing: '-0.01em' }],
        callout: ['16px', { lineHeight: '21px', fontWeight: '400', letterSpacing: '-0.01em' }],
        subhead: ['15px', { lineHeight: '20px', fontWeight: '400', letterSpacing: '-0.01em' }],
        footnote: ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'caption-1': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'caption-2': ['11px', { lineHeight: '13px', fontWeight: '400' }],
        'value-lg': ['28px', { fontWeight: '600' }],
        display: ['36px', { lineHeight: '42px', fontWeight: '500' }],
      },
      boxShadow: {
        sm: '0 1px 4px rgba(0, 0, 0, 0.05)',
        md: '0 2px 8px rgba(0, 0, 0, 0.08)',
        lg: '0 4px 16px rgba(0, 0, 0, 0.12)',
      },
    },
  },
  plugins: [],
}
